meta_product_name: "Hedononoia"
meta_title: "Alex Weird: The Absurdest Absurdist"
meta_description: "A library of works and ongoing projects by Alex Weird."
meta_image: "babs-compo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"
