Rails.application.routes.draw do
  root to: 'pages#landing'
  get 'music/om', to: 'music#om', as: 'om'
  get 'music/aw', to: 'music#aw', as: 'aw'
  get '/home', to: 'pages#home'
  get 'pages/home', to: 'pages#home'
  get '/music', to: 'pages#music'
  get 'pages/music', to: 'pages#music'
  get '/images', to: 'pages#images'
  get 'pages/images', to: 'pages#images'
  get 'images/photos', to: 'images#photos'
  get '/photos', to: 'images#photos'
  get 'images/graphics', to: 'images#graphics'
  get '/graphics', to: 'images#graphics'
  get 'images/gals-point-guns', to: 'images#gals_point_guns'
  get '/gals-point-guns', to: 'images#gals_point_guns'
  get 'writings', to: 'pages#writings'
  get 'pages/writings', to: 'pages#writings'
  get 'writings/fake-albums', to: 'writings#fake_albums'
  get 'fake-albums', to: 'writings#fake_albums'
  get 'writings/word-salad', to: 'writings#word_salad'
  get 'word-salad', to: 'writings#word_salad'
  get '/fake-albums/butane', to: 'writings#butane'
  get 'fake-albums/porta-xan', to: 'writings#porta_xan'
  get 'fake-albums/pleasant-surprise', to: 'writings#pleasant_surprise'
  get 'fake-albums/cookies', to: 'writings#cookies'
  resources :videos, only: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
